db-setup-script: "script.sql"
schema-name: "bohdan_boretskyi_smartcap"

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mvc:  # the fix for swagger
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  swagger-ui:
    enabled: true
    layout: BaseLayout
    path: /swagger-ui.html
    operationsSorter: method

jwt:
  token:
    secret: acorn
    expired: 3600000

server:
  port: 80


